/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author saiko
 */
public class InitDlg extends javax.swing.JDialog {
    
    // Attributs
    
    private LesJoueurs lj; //Les joueurs sélectionnés
    private boolean ok; //L'indicateur de fermeture
    private int nc; // Le niveau du jeu (4,10,18,32)
    
    // Constructeurs
    
    public InitDlg(Frame parent, boolean modal) {
        super(parent, modal);// Appel du constructeur de la classe ancêtre ici JDialog
        initComponents();
        this.nc = 4;
        this.lj = new LesJoueurs();
        this.ok = false;
    }
    
    // Accesseurs 
    public LesJoueurs getJoueurs()
    {
        return this.lj;
    }
    public boolean getOk()
    {
        return this.ok;
    }
    public int getNiveau()
    {
        return this.nc;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Taille = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LTaille = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Enfant = new javax.swing.JRadioButton();
        Debutant = new javax.swing.JRadioButton();
        Avance = new javax.swing.JRadioButton();
        Expert = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        LJoueur = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        CLara = new javax.swing.JCheckBox();
        CJack = new javax.swing.JCheckBox();
        CJean = new javax.swing.JCheckBox();
        CAmadeus = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel1.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel1.add(Valider);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel2.add(jScrollPane1);

        BPhoto.setPreferredSize(getPreferredSize());
        BPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPhotoActionPerformed(evt);
            }
        });
        jPanel2.add(BPhoto);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jPanel4.setLayout(new java.awt.BorderLayout());

        LTaille.setText("Choisissez la taille du jeu");
        jPanel4.add(LTaille, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        Taille.add(Enfant);
        Enfant.setSelected(true);
        Enfant.setText("Enfant ( 4 personnages, 2 familles )");
        Enfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnfantActionPerformed(evt);
            }
        });
        jPanel5.add(Enfant);

        Taille.add(Debutant);
        Debutant.setText("Débutant ( 10 personnages, 4 familles )");
        Debutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebutantActionPerformed(evt);
            }
        });
        jPanel5.add(Debutant);

        Taille.add(Avance);
        Avance.setText("Avancé ( 18 personnages, 6 familles )");
        Avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanceActionPerformed(evt);
            }
        });
        jPanel5.add(Avance);

        Taille.add(Expert);
        Expert.setText("Expert ( 32 personnages, 6 familles )");
        Expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertActionPerformed(evt);
            }
        });
        jPanel5.add(Expert);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        jPanel6.setLayout(new java.awt.BorderLayout());

        LJoueur.setText("Choisissez les joueurs créés par défaut");
        jPanel6.add(LJoueur, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.GridLayout(4, 1));

        CLara.setText("Lara");
        CLara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLaraActionPerformed(evt);
            }
        });
        jPanel7.add(CLara);

        CJack.setText("Jack");
        CJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CJackActionPerformed(evt);
            }
        });
        jPanel7.add(CJack);

        CJean.setText("Jean-Sébastien");
        CJean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CJeanActionPerformed(evt);
            }
        });
        jPanel7.add(CJean);

        CAmadeus.setText("Amadeus");
        CAmadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAmadeusActionPerformed(evt);
            }
        });
        jPanel7.add(CAmadeus);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnfantActionPerformed
        // Gestionnaire de la selection de Enfant
        this.nc = 4;//Niveau Enfant 4 Personnages (8 cartes)
    }//GEN-LAST:event_EnfantActionPerformed

    private void DebutantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebutantActionPerformed
        // Gestionnaire de la selection de Debutant
        this.nc = 10;//Niveau Debutant 10 Personnages (20 cartes)
    }//GEN-LAST:event_DebutantActionPerformed

    private void AvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanceActionPerformed
        // Gestionnaire de la selection de Avance
        this.nc = 18;//Niveau Avancé 18 Personnages (36 cartes)
    }//GEN-LAST:event_AvanceActionPerformed

    private void ExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertActionPerformed
        // Gestionnaire de la selection de Expert
        this.nc = 32;//Niveau Expart 32 Personnages (64 cartes)
    }//GEN-LAST:event_ExpertActionPerformed

    private void CLaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLaraActionPerformed
        // Gestionnaire du clic sur la case Lara
        Joueur j=new Joueur("Lara", "epiques");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img)); 
    }//GEN-LAST:event_CLaraActionPerformed

    private void CJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CJackActionPerformed
        // Gestionnaire du clic sur la case Jack
        Joueur j=new Joueur("Jack", "rares");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/jack.png")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CJackActionPerformed

    private void CJeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CJeanActionPerformed
        // Gestionnaire du clic sur la case Jean-Sébastien
        Joueur j=new Joueur("Jean-Sébastien", "alpins-femmes");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/bach.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CJeanActionPerformed

    private void CAmadeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAmadeusActionPerformed
        // Gestionnaire du clic sur la case Asmadeus
        Joueur j=new Joueur("Amadeus", "communs");
        j.setPhoto(new ImageIcon(getClass().getResource("/img/mozart.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CAmadeusActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        //Gestionnaire du clic sur Annuler
        this.ok = false;
        this.setVisible(false);//Fermer la fenêtre
        this.dispose();//Libérer l'espace mémoire
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // Gestionnaire du clic sur Valider
        Joueur j;
        if(CLara.isSelected())
        {
            j = new Joueur("Lara","epiques");
            j.setPhoto(new ImageIcon(getClass().getResource("/img/lara.jpg")));
            //Ajout du joueur dans la liste des joueurs 
            this.lj.ajouteJoueur(j);
        }
        if(CJack.isSelected())
        {
            j = new Joueur("Jack","rares");
            j.setPhoto(new ImageIcon(getClass().getResource("/img/jack.png")));
            //Ajout du joueur dans la liste des joueurs 
            this.lj.ajouteJoueur(j);
        }
        if(CJean.isSelected())
        {
            j = new Joueur("Jean-Sébastien", "alpins-femmes");
            j.setPhoto(new ImageIcon(getClass().getResource("/img/bach.jpg")));
            //Ajout du joueur dans la liste des joueurs 
            this.lj.ajouteJoueur(j);
        }
        if(CAmadeus.isSelected())
        {
            j = new Joueur("Amadeus", "communs");
            j.setPhoto(new ImageIcon(getClass().getResource("/img/mozart.jpg")));
            //Ajout du joueur dans la liste des joueurs 
            this.lj.ajouteJoueur(j);
        }
        
        this.ok = true;
        this.setVisible(false);//Fermer la fenêtre
        this.dispose();//Libérer l'espace mémoire
    }//GEN-LAST:event_ValiderActionPerformed

    private void BPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JRadioButton Avance;
    private javax.swing.JButton BPhoto;
    private javax.swing.JCheckBox CAmadeus;
    private javax.swing.JCheckBox CJack;
    private javax.swing.JCheckBox CJean;
    private javax.swing.JCheckBox CLara;
    private javax.swing.JRadioButton Debutant;
    private javax.swing.JTextArea Edition;
    private javax.swing.JRadioButton Enfant;
    private javax.swing.JRadioButton Expert;
    private javax.swing.JLabel LJoueur;
    private javax.swing.JLabel LTaille;
    private javax.swing.ButtonGroup Taille;
    private javax.swing.JButton Valider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
