/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
    import java.util.ArrayList;
    import javax.swing.*;
    import java.awt.*;
/**
 *
 * @author saiko
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {
    
    //Attributs
    
        private Joueur Newgamer;// Le Joueur qui sera créé
        private boolean sortie;// Indiquera comment a été fermée la boîte de dialogue
        ImageIcon photo;// pour la photo du Joueur
        LesPersonnages lp = new LesPersonnages();// liste des personnages
        
    //Accesseurs
        
        public Joueur getJoueur ()
        {
            // Retourne le joueur créé
            return this.Newgamer;
        }
        public boolean getSortie ()
        {
            // La valeur est à false si la fenêtre a été fermé sans création de joueur : annuler
            // La valeur est à true si la fenêtre a été fermé avec création de joueur : confirmer
            return this.sortie;
        }
        
   // Constructeurs
        
    public SaisieJoueurDlg(Frame parent, boolean modal, LesPersonnages liste) {
        super(parent, modal);// Appel du constructeur de l'ancêtre
        this.lp = liste; // Récupération de la liste des personnages
        initComponents();// Création de l'interface par l'EDI
        initListeFamilles();// Initialisation de la liste des familles
    }

    //Méthodes
    
    public void initListeFamilles()
    {
        // Initialisation de la liste des familles
        DefaultListModel mod = new DefaultListModel();// Création du modèle
        ArrayList<String> liste = lp.getFamilles();// Récupération de la liste des familles
        for(int i=0; i<liste.size();i++)
            mod.addElement(liste.get(i));// Les familles sont ajoutés au modèle
        ListeFamilles.setModel(mod);//Affichage sur l'interface
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Pseudo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeFamilles = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Parcourir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Créez votre joueur !!");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Donnez votre Pseudo !");
        jPanel5.add(jLabel2, java.awt.BorderLayout.NORTH);
        jPanel5.add(Pseudo, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Quelle est votre Famille préférée de personnages ?");
        jPanel6.add(jLabel3, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(ListeFamilles);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Choisissez une photo !");
        jPanel7.add(jLabel4, java.awt.BorderLayout.NORTH);

        Parcourir.setText("Parcourir");
        Parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcourirActionPerformed(evt);
            }
        });
        jPanel7.add(Parcourir, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(Photo, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel8.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel8.add(Valider);

        jPanel4.add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcourirActionPerformed
        // Gestionnaire du clic sur le bouton Parcourir
         JFileChooser jf= new JFileChooser();
        // « JFileChooser » est la boîte de sélection d’un fichier, elle retourne un objet de type « File »
         if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
         {              
            String path = jf.getSelectedFile().getPath();
            // « JFileChooser » est la boîte de sélection d’un fichier, elle retourne un objet de type « File »
            Image img = Toolkit.getDefaultToolkit().getImage(path);
            //Récuperation de l'image sélectionnée
            img = img.getScaledInstance(Photo.getWidth()-10, Photo.getHeight()-10, Image.SCALE_DEFAULT);
            photo = new ImageIcon(img); 
            Photo.setIcon(photo);
            //Affichage de l'image sur le bouton Photo
         }
    }//GEN-LAST:event_ParcourirActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // Gestionnaire du clic sur le bouton Annuler
        this.sortie = false;
        this.setVisible(false);//Fermer la fenêtre
        this.dispose();//Libérer l'espace mémoire
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // Gestionnaire du clic sur le bouton Valider
        String pseudo = this.Pseudo.getText();//Récupération du pseudo
        if(pseudo.equals("") || pseudo.equals("Erreur!! Pseudo Vide"))
        {
            // Si le pseudo est vide
            this.Pseudo.setText("Erreur!! Pseudo Vide");// Affichage d'un message d'erreur
            this.Pseudo.setBorder(BorderFactory.createLineBorder(Color.red));// La Bordure devient Rouge
        }
        else
        {   
            // Si le pseudo est saisi
            String famille = ListeFamilles.getSelectedValue();// Récupération de la famille sélectionnée
            if(!famille.equals(""))
            {
                // Si une famille est selectionnée 
                this.Newgamer = new Joueur(pseudo, famille);// Création du joueur
                if(this.photo != null)
                    // Si une photo est sélectionnée
                    this.Newgamer.setPhoto(photo);// On attribue la photo au joueur
                else
                    // Si aucune n'est sélectionnée on attribue la photo par défaut
                    this.Newgamer.setPhoto(new ImageIcon(getClass().getResource("/img/joueurDefault.png")));
                this.sortie = true;
                this.setVisible(false);//Fermer la fenêtre
                this.dispose();//Libérer l'espace mémoire
            }
        }
    }//GEN-LAST:event_ValiderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JList<String> ListeFamilles;
    private javax.swing.JButton Parcourir;
    private javax.swing.JButton Photo;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
