/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author saiko
 */
public class VisuPersonnagesDlg extends javax.swing.JDialog {

    //Attributs
   
    private Joueur joueur;
    
    //Constructeur
    
    public VisuPersonnagesDlg(Frame parent, boolean modal, Joueur j) 
    {
        super(parent, modal);
        initComponents();
        this.joueur = j;
        this.Titre.setText("Cartes du Joueur : "+this.joueur.getPseudo());
        this.Score.setText("Score : "+this.joueur.getScore());
        initPanneau();// Compléter le panneau avec les boutons
    }

    //Méthodes
    
    public void initPanneau()
    {
        int nb = this.joueur.getPacket().getTaille();
        int c = (int)(Math.sqrt(2*nb));
        //Fixer la disposition du tableau
        if(c != 0)
            Panneau.setLayout(new GridLayout(c,c));
        else
            Panneau.setLayout(new GridLayout(1,1));
        //Initialisation du plateau
        PanneauImage panneau;
        for(int i = 0; i < nb; i++)
        {
            panneau = new PanneauImage();
            panneau.setImage(this.joueur.getPacket().getPerso(i).getPhoto());
            this.Panneau.add(panneau);
        }
        this.pack();//à appeler si ajout ou suppression de composants 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        Panneau = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        Titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Titre);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));
        jPanel3.add(Score);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel Score;
    private javax.swing.JLabel Titre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
