/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author saiko
 */
public class VisuJoueursDlg extends javax.swing.JDialog {

    //Attributs
    
    private LesJoueurs lesJoueurs; //Liste des joueurs qui sera transmis par le onstructeur
    
    //Constructeurs
    
    public VisuJoueursDlg(Frame parent, boolean modal, LesJoueurs lj) {
        super(parent, modal);//Appel du constructeur de la classe ancêtre
        initComponents();//Interface
        //Initialisation de l'attribut avec paramètre du constructeur
        this.lesJoueurs = lj;
        //Completer l'interface avec la construction des boutons
        initTrombi();
    }
    
    //Méthodes
    
    public void initTrombi()
    {
        // Récuperation du nombre de Joueurs
        int nb = this.lesJoueurs.getNbJoueurs();    
        // Fixer la disposition du tableau
        Panneau.setLayout(new GridLayout(1,nb));
        // Création des BoutonImage
        for(int i = 0; i < nb; i++)
        {
            BoutonImage jb = new BoutonImage();
            jb.setName(""+i);
            Joueur j = this.lesJoueurs.getJoueur(i);
            jb.setImage(j.getPhoto().getImage());
            //Abonnement du bouton à un écouteur de type ActionListener
            jb.addActionListener(
                new java.awt.event.ActionListener()
                {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                        //methode éxécuté quand on clique sur le bouton
                        AfficheInfosJoueur(evt);
                    }
                }           
            );
            Panneau.add(jb);
        }
        this.pack(); // à appeler si ajout ou suppression de composants 
    }
    
    private void AfficheInfosJoueur(java.awt.event.ActionEvent evt)
    {
        //Récupération du composant qui a déclenché l'action
       BoutonImage jb = (BoutonImage) evt.getSource();
       int ind = Integer.parseInt(jb.getName());
       //Recupération du Joueur
       Joueur j = this.lesJoueurs.getJoueur(ind);
       //Affichage des infos
       Edition.setText(j.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panneau = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        Edition.setEditable(false);
        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.EAST);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choisissez un joueur pour voir ses caractéristiques !");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Edition;
    private javax.swing.JPanel Panneau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
